### DISCUSSION TITLE
How to invalidate an key?

### DISCUSSION THREAD

**Discussion by axel7083** [coil-kt/coil#3021] [General]
I am using an url for user avatar, which is something like `/v1/avatar/{user_id}` and the user can update its own avatar, and I would like the display image to update, what are my options?

I was looking for a way to invalidate the key, but in the version I am using I don't see an `invalidate` function on my ImageLoader.

---

Some info

Using compose multiplatform, with the following versions

```toml
[versions]
coil = "3.2.0"
compose-multiplatform = "1.8.0"

[libraries]
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
```

---

My best tentative so far is doing the following

```ktolin
imageLoader.diskCache?.remove(key);
imageLoader.memoryCache?.remove(MemoryCache.Key(key))
```

but this only works after the user leave the page and come back :/
