### ISSUE TITLE
Image from url never shows? - Tried `SubcomposeAsyncImage` and `AsyncImage`

### ISSUE THREAD

**Issue by SamuelMarks** [coil-kt/coil#2521]
**Describe the bug**
A clear and concise description of what the bug is. **Please [enable logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) and attach any stack traces.** Bug reports without reproduction steps are likely to be closed.

**To Reproduce**
```kotlin
AsyncImage(
    model = imageFrontUrl,
    placeholder = painterResource(Res.drawable.compose_multiplatform),
    contentDescription = "product photo",
    contentScale = ContentScale.Crop,
    // modifier = Modifier.clip(CircleShape)
)
```
```kotlin
Box {
    SubcomposeAsyncImage(
        model = imageFrontUrl,
        loading = {
            CircularProgressIndicator()
        },
        contentDescription = "Product image",
    )
}
```

Where `imageFrontUrl` isn't known ahead of time, but I've confirmed with `println` that it is a valid value. For example:
https://images.openfoodfacts.org/images/products/003/400/004/0810/front_en.3.400.jpg

**Logs/Screenshots**
No errors or issues

**Version**
Compose UI (Android, iOS, web, desktop)
```toml
[versions]
# others omitted for brevity
kotlin = "2.0.20"
kotlinx-coroutines = "1.8.1"
# openfoodfactsKotlin = "1.0-SNAPSHOT"
playServicesCodeScanner = "16.1.0"
ktor = "3.0.0-rc-1"
coroutines = "1.9.0"

[libraries]
# others omitted for brevity
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor", version.ref = "coilCompose" }
coil3-coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
```

FWIW, the aforementioned code is all wrapped up like so:
```kotlin
LaunchedEffect(barcode) {
    try {
        val product = scope.async {
            openFoodFactsApi.productById(barcode)
        }.await().product
        productName = product?.productName ?: "no generic name"
        if (product?.imageFrontUrl != null) {
            imageFrontUrl = product.imageFrontUrl
        }
    } catch (e: CancellationException) {
        currentCoroutineContext().ensureActive()
    } catch (e: HttpResponseException) {
        errorText = "[${e.response.status}] ${e.response.bodyAsText()}"
        println("Set errorText to $errorText")
    }
}
AnimatedVisibility(productName.isNotEmpty()) {
```
